//defines.h
#define READBIT(WORD,BIT) ((WORD>>BIT)&1)
#define WRITENIBBLE(WORD,NIBBLESTARTBITPOS,VAL) \
        WORD=((WORD&~(15<<NIBBLESTARTBITPOS))| \
		          (((VAL&15)<<NIBBLESTARTBITPOS)));

#define READNIBBLE(WORD,NIBBLESTARTBIT) \
        ((WORD>>NIBBLESTARTBIT)&15)
				
#define WRITEBYTE(WORD,BYTESTARTBITPOS,VAL) \
        WORD=((WORD&~(255<<BYTESTARTBITPOS))| \
		          (((VAL&255)<<BYTESTARTBITPOS)));

#define WRITEBIT(WORD,BITPOS,BIT) \
        WORD=((WORD&~(1<<BITPOS))|(((BIT<<BITPOS))));


